### ISSUE TITLE
in search, some bus stops appear with showing distance, others not.

### ISSUE THREAD

**Issue by sderungs99** [sderungs99/sglandtransport#79] opened 2020-06-27 05:39 UTC
In search, we should not show distance. I remember in our current production app, this was resolved by keeping 2 separate bus stop lists, as when you keep only 1 list, the updates you do apply for both search and nearby, because updates are done by reference.

**Comment by bobrenji** [comment] 2020-06-28 07:40
Not able to reproduce the issue. So for time now, I will close this.

**Closed by bobrenji** 2020-06-28 07:40 UTC
Labels: bug
